### ISSUE TITLE
Connecting Hydration Stats

### ISSUE THREAD

**Issue by conconartist** [srslie/fitlit#5]
**Describe the bug/issue**

For the Hydration and CommunityHydration classes, I believe the methods and constructor are set up correctly to access the data from hydration.js.  However, connecting to the data via scripts.js is not resulting in the outcome I'm hoping for, so I'm assuming that there's something missing in how it's currently trying to access the data to display.  

**To Reproduce (if bug)**
1. Go to scripts.js, open in text editor
3. Scroll down to showHydrationStats and showHydrationStatsWeek to view functions.  (Scroll up to top for instantiations of classes).  
4. See error: Right now, I have the interpolations as placeholders since they are not accurately accessing the methods at this point.  

**Expected behavior**
When opening the index in the browser, you should see stats on window load under the category for water that show the water consumed for the day.  Under the graph section, you should see on load the weekly statistics for water consumption for the user on each day of a given week.  

**As a** user, **When I visit** the home view page for "Luisa", **I want to** see user stats for water consumption on a given day and given week.

**Comment by srslie** [comment]
I added some comments in the PR, the main issue was just a query selector for a class that wasn't yet in the HTML!
