### ISSUE TITLE
Iteration 3 - Sleep

### ISSUE THREAD

**Issue by srslie** [srslie/fitlit#8]
**Describe the bug/issue**
- CommunitySleep class is not passing all tests

**To Reproduce (if bug)**
1. run ```npm test tests/CommunitySleep-test.js```
2. see errors: 
```
 TypeError: Cannot read property 'to' of undefined
 TypeError: communitySleep.calculateSleepQualityWeek is not a function
 TypeError: communitySleep.calculateAvgSleepQuality is not a function
 TypeError: communitySleep.findBestQualitySleepers is not a function
 TypeError: communitySleep.findMostHrsSleepers is not a function
```

**Expected behavior**
- The first error should actually run the test for calculateSleepWeek, though it will come back as an unexpected return since calculateSleepWeek is declared but returns no values.
- The other functions are not yet declared so will continue to show that TypeError.

**Additional context**
- The first error can be fixed by changing the parentheses around the function calls. 
```
 expect(communitySleep.calculateSleepWeek(40, "2019/08/10", "2019/08/16").to.deep.equal([4.1, 4.8, 3.4, 9.2, 6.0, 6.8, 9.3]));
```
The way it's written, the expect() needs to only contain the cs.csw(#) like " expect( cs.csw(#) ) " 
so it should be:
```
 expect(communitySleep.calculateSleepWeek(40, "2019/08/10", "2019/08/16")).to.deep.equal([4.1, 4.8, 3.4, 9.2, 6.0, 6.8, 9.3]);
```

- The functions that haven't been written yet remind me closely of ones from iteration 4 and I highly recommend reviewing parallels. 
    - for the functions to grab stuff for the week, CommunityActivity has this which might help:
```
 findWeekActivities(startDate, endDate, user) {
    const startNum = this.dateToNumber(startDate)
    const endNum = this.dateToNumber(endDate)
    const userActivities = this.findAllUserActivities(user)
    return userActivities.filter(activity => {
      const activityDateNum = this.dateToNumber(activity.date)
      return activityDateNum >= startNum && activityDateNum <= endNum
    })
  }
```

 -  Once we get a week's worth of the sleep data as an array of [sleep, sleep, sleep], we can probably get a total hours slept (via reduce) and array of just the sleep qualities each day (via map) fairly easily
    - The average for all users sleep quality is close to the CommunityAverage method:

```
 findCommunityAverage(date, fitnessType) {
    const allActivitesForDate = this.activities.filter(activity => activity.date === date)
    const totalActivity = allActivitesForDate.reduce((activityTotal, activity) => activityTotal + activity[fitnessType], 0)

    return Math.round(totalActivity / allActivitesForDate.length)
  }
```

- For the users who average sleep quality > 3 for a week, that's a tricky one to get, but if you're interested in my pseudocode thought, I might break it down like:
  - the function takes in a startDate, endDate, and arrayOfUsers
  - calls a function similar to findWeekActivites()  for each user's userID in the arrayOfUsers (we can call it using our userRepository), return an array of all users sleep within that week
   - again using the array of users for each userID, we reduce to get each user's average sleep within that weekofCommunitySleep array,  and return both the average and the userID
   - we filter that array of averagesAndIDs for ones over 3, and get a returned array of just those users who average that good sleep quality (not me, clearly)
    - we use all those ids to grab those users (their names, or whatever) from the userRepository using the method in that class  ```UserRepository.getUserData(id)```

- For the given day users that slept the most, CommunityActivity has this which might help:
```
findRecordStairs(user) {
    const userActivities = this.findAllUserActivities(user)
    const allStairsClimbed = userActivities.map(activity => activity.stairsClimbed)
    return Math.max(...allStairsClimbed)
  }
```

- it looks like the two methods that get averages you have written for average sleep hours for a day and quality for a day are basically the same function. What if they intook a 'sleepAttribute' parameter and we could call sleeper[sleepAttribute] to return either the hours or quality?

- Overall the stuff you have looks solid! Thanks for getting those up!

- I'm going to do a little bit of rearranging of the html, css, and scripts mainly to just display the charts for each of these, and I'm making some helper functions to be able to parse the return values of the sleep hours and quality over the course of the week into those charts easily -- getData() and chartIt()
- I might also mess with the extensions. I'm doing a few mid-mod assessment prep things tomorrow so I'll see what I get done!

**Comment by conconartist** [comment]
@srslie Thanks for the detailed feedback--- I should have everything refactored to the point where the methods function correctly now and I'm hoping to refactor for duplicate functions that you mentioned when/if we have the time.  Let me know if I missed anything!
